spring.application.name=api-gateway
server.port=8080
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://swiftbank-user:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
spring.cloud.gateway.routes[1].id=account-service
spring.cloud.gateway.routes[1].uri=http://swiftbank-account:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/accounts/**
spring.cloud.gateway.routes[2].id=transaction-service
spring.cloud.gateway.routes[2].uri=http://swiftbank-transaction:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/transactions/**
jwt.secret=${JWT_SECRET:swiftbank-super-secret-jwt-key-2024-make-this-long}
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:swiftbank-redis}
spring.data.redis.port=6379
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:redis123}
logging.level.org.springframework.cloud.gateway=DEBUG